apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  mysql-server: "mysql-service.monit"    # The name of mysql service
  mysql-database-name: "testdb"     # The name of the database used by the demo app
  username: "root"
  